export const dummyData = {
  customerInfos: [
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
    {
      hubspot: {
        properties: {
          createdate: "2021-12-05T19:16:15.215Z",
          email: "cras.lorem@aol.ca",
          firstname: "Lila",
          hs_object_id: "102",
          lastmodifieddate: "2021-12-05T19:16:26.759Z",
          lastname: "Gonzalez",
          company: "Thoughtbridge",
          phone: "123-4567",
        },
      },
      stripe: {
        id: "cus_KiqxwhePMNNofZ",
        object: "customer",
        address: {
          city: "Samos",
          country: "ES",
          line1: "Ctra. de Siles 98",
          line2: "",
          postal_code: "27620",
          state: "LU",
        },
        balance: 0,
        created: 1638728169,
        currency: null,
        default_source: null,
        delinquent: false,
        description: null,
        discount: null,
        email: "cras.lorem@aol.ca",
        invoice_prefix: "4F2C409A",
        invoice_settings: {
          custom_fields: null,
          default_payment_method: null,
          footer: null,
        },
        livemode: false,
        metadata: {},
        name: "Lila Gonzalez",
        next_invoice_sequence: 1,
        phone: "+912835615453",
        preferred_locales: [],
        shipping: null,
        tax_exempt: "none",
      },
    },
  ],
};
